# Generated by Django 5.1 on 2024-09-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('TaskId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('State', models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('ExpirationDate', models.DateField()),
            ],
        ),
    ]
